//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.Reports
{
    public partial class ReportCustomerByUser
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.ScriptManager ScriptManager1;

        protected global::System.Web.UI.WebControls.Label lblUserId;

        protected global::System.Web.UI.WebControls.TextBox txtUserId;

        protected global::System.Web.UI.WebControls.Button btnRun;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::Microsoft.Reporting.WebForms.ReportViewer ReportViewer1;
    }
}
