<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="User.aspx.cs" Inherits="WebForm.Presentation.User" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Formulario Usuario</title>
    <style>
        body {
            background-color: #f4f4f4;
            font-family: Arial, sans-serif;
        }

        .form-container {
            background-color: white;
            padding: 30px;
            margin: 60px auto;
            width: 400px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
            border-radius: 8px;
        }

        h2 {
            text-align: center;
            margin-bottom: 25px;
            color: #333;
        }

        table {
            width: 100%;
        }

        td {
            padding: 10px;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }

        .btn-center {
            text-align: center;
        }

        input[type="submit"],
        input[type="button"],
        .aspNet-Button {
            padding: 10px 20px;
            background-color: #0078d4;
            border: none;
            color: white;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type="submit"]:hover,
        .aspNet-Button:hover {
            background-color: #005fa3;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="form-container">
            <h2>Formulario Usuario</h2>
            <table>
                 <tr >
                     <td><asp:Label ID="lblID_USE" runat="server" Text="ID:"></asp:Label></td>
                     <td>
                         <asp:TextBox ID="ID_USE" runat="server" Enabled="False"></asp:TextBox></td>
                 </tr>
                <tr>
                    <td><asp:Label ID="lblNAM_USE" runat="server" Text="Nombre:"></asp:Label></td>
                    <td><asp:TextBox ID="NAM_USE" runat="server"></asp:TextBox></td>
                </tr>
                <tr>
                    <td><asp:Label ID="lblLAS_USE" runat="server" Text="Apellido:"></asp:Label></td>
                    <td><asp:TextBox ID="LAS_USE" runat="server"></asp:TextBox></td>
                </tr>
                <tr>
                    <td><asp:Label ID="lblIDC_USE" runat="server" Text="Cédula:"></asp:Label></td>
                    <td><asp:TextBox ID="IDC_USE" runat="server"></asp:TextBox></td>
                </tr>
                <tr>
                    <td><asp:Label ID="lblADD_USE" runat="server" Text="Dirección:"></asp:Label></td>
                    <td><asp:TextBox ID="ADD_USE" runat="server"></asp:TextBox></td>
                </tr>
                <tr>
                    <td><asp:Label ID="lblPAS_USE" runat="server" Text="Contraseña:"></asp:Label></td>
                    <td><asp:TextBox ID="PAS_USE" runat="server" TextMode="Password"></asp:TextBox></td>
                </tr>
                <tr>
                    <td colspan="2" class="btn-center">
                        <asp:Button 
    ID="btnBuscar" 
    runat="server" 
    Text="Buscar" 
    CssClass="btn btn-primary" 
    OnClick="btnBuscar_Click" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="btn-center">
                        <asp:Button ID="btnLogout" runat="server" Text="Cerrar Sesión" CssClass="aspNet-Button" OnClick="btnLogout_Click" /><asp:Button ID="btnUpdate" runat="server" Text="Update" CssClass="aspNet-Button" OnClick="btnUpdate_Click" />
                    </td>
                </tr>
            <asp:TextBox 
    ID="txtBuscarCedula" 
    runat="server" 
    CssClass="form-control" 
    placeholder="Buscar cédula…" />
            <asp:GridView runat="server" ID="gvUser" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="ID_USE"  AutoGenerateSelectButton="True" OnRowDeleting="gvUser_RowDeleting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                <Columns>
                    <asp:BoundField DataField="ID_USE" HeaderText="ID" Visible="True"></asp:BoundField>
                    <asp:BoundField DataField="NAM_USE" HeaderText="NAME"></asp:BoundField>
                    <asp:BoundField DataField="LAS_USE" HeaderText="APELLIDO"></asp:BoundField>
                    <asp:BoundField DataField="IDC_USE" HeaderText="CEDULA"></asp:BoundField>
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
